---

name: workflow-application-token-action
description: Obtain a temporary access token for a GitHub Application when running in a GitHub Actions Workflow.
author: peter-murray

inputs:
  application_private_key:
    description: GitHub Application Private Key value.
    required: true

  application_id:
    description: GitHub Application ID value.
    required: true

  organization:
    description: The GitHub Organization to get the application installation for, if not specified will use the current repository instead
    required: false

outputs:
  token:
    description: A valid token representing the Application that can be used to access what the Application has been scoped to access.

runs:
  using: node12
  main: dist/index.js

branding:
  icon: lock
  color: green